import { SdkGenerator } from "./index.js";

export class GoGenerator implements SdkGenerator {
  getFileExtension(): string {
    return '.go';
  }

  generate(spec: any): string {
    let sdkCode = `// Code generated by SocketDocs SDK Generator v${spec.specVersion}. DO NOT EDIT.\n\n`;
    sdkCode += `package socketdocs\n\n`;
    sdkCode += `import (\n\t"encoding/json"\n\t"fmt"\n)\n\n`;
    
    sdkCode += `type Client struct {\n\tconn interface{}\n}\n\n`;
    sdkCode += `func NewClient(conn interface{}) *Client {\n\treturn &Client{conn: conn}\n}\n\n`;

    for (const nsName in spec.namespaces) {
      const ns = spec.namespaces[nsName];
      for (const eventName in ns.events) {
        const event = ns.events[eventName];
        if (event.direction === "client_to_server" || event.direction === "bidirectional") {
          const capitalized = eventName.charAt(0).toUpperCase() + eventName.slice(1);
          sdkCode += `func (c *Client) ${capitalized}(payload interface{}) error {\n`;
          sdkCode += `\tfmt.Printf("Emitting ${eventName}: %v\\n", payload)\n`;
          sdkCode += `\treturn nil\n`;
          sdkCode += `}\n\n`;
        }
      }
    }
    return sdkCode;
  }
}
