import { SdkGenerator } from "./index";

export class PhpGenerator implements SdkGenerator {
  getFileExtension(): string {
    return '.php';
  }

  generate(spec: any): string {
    let sdkCode = `<?php\n\n// Generated by SocketDocs SDK Generator v${spec.specVersion}\n\n`;
    sdkCode += `namespace SocketDocs;\n\n`;
    sdkCode += `class SocketDocsClient {\n`;
    sdkCode += `    private $socket;\n\n`;
    sdkCode += `    public function __construct($socket) {\n`;
    sdkCode += `        $this->socket = $socket;\n`;
    sdkCode += `    }\n\n`;

    for (const nsName in spec.namespaces) {
      const ns = spec.namespaces[nsName];
      sdkCode += `    // Namespace: ${nsName}\n`;
      for (const eventName in ns.events) {
        const event = ns.events[eventName];
        if (event.direction === "client_to_server" || event.direction === "bidirectional") {
          sdkCode += `    public function ${eventName}($payload) {\n`;
          sdkCode += `        echo "Emitting ${eventName}: " . json_encode($payload) . PHP_EOL;\n`;
          sdkCode += `        $this->socket->emit("${eventName}", $payload);\n`;
          sdkCode += `    }\n\n`;
        }
      }
    }
    sdkCode += `}\n`;
    return sdkCode;
  }
}
