import { SdkGenerator } from "./index.js";

export class PythonGenerator implements SdkGenerator {
  getFileExtension(): string {
    return '.py';
  }

  generate(spec: any): string {
    let sdkCode = `# Generated by SocketDocs SDK Generator v${spec.specVersion}\n\n`;
    sdkCode += `class SocketDocsClient:\n`;
    sdkCode += `    def __init__(self, socket):\n`;
    sdkCode += `        self.socket = socket\n\n`;

    for (const nsName in spec.namespaces) {
      const ns = spec.namespaces[nsName];
      for (const eventName in ns.events) {
        const event = ns.events[eventName];
        if (event.direction === "client_to_server" || event.direction === "bidirectional") {
          sdkCode += `    def ${eventName}(self, payload):\n`;
          sdkCode += `        print(f"Emitting ${eventName}: {payload}")\n`;
          sdkCode += `        self.socket.emit("${eventName}", payload)\n\n`;
        }
      }
    }
    return sdkCode;
  }
}
