import { SdkGenerator } from "./index";

export class TypescriptGenerator implements SdkGenerator {
  constructor(private lang: 'ts' | 'js') {}

  getFileExtension(): string {
    return this.lang === 'ts' ? '.ts' : '.js';
  }

  generate(spec: any): string {
    let sdkCode = `// Generated by SocketDocs SDK Generator v${spec.specVersion}\n\n`;
    sdkCode += `export class SocketDocsClient {\n`;
    sdkCode += `  constructor(private socket: any) {}\n\n`;

    for (const nsName in spec.namespaces) {
      const ns = spec.namespaces[nsName];
      sdkCode += `  // Namespace: ${nsName}\n`;
      for (const eventName in ns.events) {
        const event = ns.events[eventName];
        if (event.direction === "client_to_server" || event.direction === "bidirectional") {
          const isRequestResponse = event.type === "request_response";
          
          sdkCode += `  ${eventName}(payload: any): ${isRequestResponse ? 'Promise<any>' : 'void'} {\n`;
          if (isRequestResponse) {
            sdkCode += `    return new Promise((resolve, reject) => {\n`;
            sdkCode += `      this.socket.emit("${eventName}", payload, (response: any) => {\n`;
            sdkCode += `        if (response && response.status === "error") reject(response);\n`;
            sdkCode += `        else resolve(response);\n`;
            sdkCode += `      });\n`;
            sdkCode += `    });\n`;
          } else {
            sdkCode += `    this.socket.emit("${eventName}", payload);\n`;
          }
          sdkCode += `  }\n`;
        }
      }
      sdkCode += `\n`;
    }
    sdkCode += `}\n`;
    return sdkCode;
  }
}
